media:
  - name: blog
    label: Blog Media
    input: media/blog
    output: /media/blog
  - name: cv
    label: Documents & CVs
    input: media/cv
    output: /media/cv

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{slug}.md"
    format: yaml-frontmatter
    fields:
      - name: title
        label: Blog titel
        type: string
        required: true
      - name: cover
        label: Blog foto
        type: image
        required: true
        options:
          media: blog
      - name: cover_image_alt
        label: Blog foto beschrijving
        type: string
      - name: date
        label: Datum gepubliceerd
        type: date
        required: true
      - name: description
        label: Blog beschrijving (kort)
        type: text
      - name: body
        label: Blog (lang)
        type: rich-text
        required: true

  - name: projects
    label: Projecten
    type: collection
    path: _projects
    filename: "{year}-{month}-{day}-{slug}.md"
    format: yaml-frontmatter
    fields:
      - name: company
        label: Bedrijf
        type: string
        required: true
      - name: logo
        label: Logo bedrijf
        type: image
        required: true
        options:
          media: blog
      - name: role
        label: Rol in project
        type: string
        required: true
      - name: tags
        label: Categorieën (Tags)
        type: select
        required: true
        options:
          multiple: true
          values:
            - name: "Energie en Mobiliteit"
              label: "Energie en Mobiliteit"
            - name: "Water"
              label: "Water"
            - name: "Duurzame Stad"
              label: "Duurzame Stad"
      - name: from-date
        label: Begin datum
        type: date
        required: true
      - name: to-date
        label: Eind datum (leeg = tot heden)
        type: date
        required: false
      - name: body
        label: Project content
        type: rich-text
        required: true

  - name: quotes
    label: Quotes
    type: collection
    path: _quotes
    filename: "{year}-{month}-{day}-{slug}.md"
    format: yaml-frontmatter
    fields:
      - name: quote-name
        label: Quote naam
        type: string
        required: true
      - name: quote
        label: Quote content (zonder "")
        type: text
        required: true
      - name: quote-date
        label: Quote datum
        type: date
        required: true


  - name: cv_singleton
    label: Huidige CV
    type: file
    path: _cv/cv.md
    format: yaml-frontmatter
    fields:
      - name: cv_file
        label: Upload nieuw CV (Alleen PDF)
        type: file
        required: false
        options:
          media: cv
          extensions: ["pdf"]