media:
  input: media/blog
  output: /media/blog

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{slug}.md"
    format: yaml-frontmatter
    fields:
      - name: title
        label: Blog titel
        type: string
        required: true
      - name: cover
        label: Blog foto
        type: image
        required: true
      - name: cover_image_alt
        label: Blog foto beschrijving
        type: string
      - name: date
        label: Datum gepubliceerd
        type: date
        required: true
      - name: description
        label: Blog beschrijving (kort)
        type: text
      - name: body
        label: Blog (lang)
        type: rich-text
        required: true
  - name: projects
    label: Projecten
    type: collection
    path: _projects
    filename: "{year}-{month}-{day}-{slug}.md"
    format: yaml-frontmatter
    fields:
      - name: company
        label: Bedrijf
        type: string
        required: true
      - name: from-date
        label: Datum van
        type: date
        required: true
      - name: to-date
        label: Datum van
        type: date
        required: false
      - name: logo
        label: Logo bedrijf
        type: image
        required: true
      - name: body
        label: Project content
        type: rich-text
        required: true