name: Breunis Urban Solutions
url: "https://therealedd.github.io"
baseurl: "/testingGround"  # <--- CRITICAL: Include the forward slash before your exact repo name

collections:
  posts:
    output: true
    permalink: /blog/:title/