# Site Settings
name: Breunis Urban Solutions
url: "https://breunisurbansolutions.nl"
baseurl: ""

# Collections Configuration
collections:
  posts:
    output: true
    permalink: /blog/:title/
  cv:
    output: false
  projects:
    output: true
    permalink: /projecten/:title/

# Default Layout assignments
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project" # Maps to _layouts/project.html automatically